### ISSUE TITLE
pod directory is not created

### ISSUE THREAD

**Issue by hangchan** [kubernetes-sigs/sig-storage-local-static-provisioner#100]
The directory for the pod does not get created.  Have to create the directory manually on the node.

```
FailedMount | MountVolume.SetUp failed for volume "local-pv-3a82f760" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -o bind /mnt/disks/disk1 /var/lib/kubelet/pods/27153f2b-7664-11e9-95b0-000af7854ba0/volumes/kubernetes.io~local-volume/local-pv-3a82f760 Output: mount: special device /mnt/disks/disk1 does not exist
```

FIX
```
mkdir /var/lib/kubelet/pods/27153f2b-7664-11e9-95b0-000af7854ba0/volumes/kubernetes.io~local-volume/local-pv-3a82f760
```

**Comment by cofyc** [comment]
hi, you shouldn't create this directory `/var/lib/kubelet/pods/27153f2b-7664-11e9-95b0-000af7854ba0/volumes/kubernetes.io~local-volume/local-pv-3a82f760`. `/var/lib/kubelet` is managed by kubelet. 

```
... Output: mount: special device /mnt/disks/disk1 does not exist
```

According to the log, please check directory `/mnt/disks/disk1`.

**Comment by hangchan** [comment]
It works after I manually create the directory and bind mount the filesystem, otherwise it gives me that error.

Here's my fstab entry
```
UUID=95d3ccf4-9445-484c-a0f9-7b1d62be8e1e /mnt/disks/disk1                  xfs     defaults,noatime,discard 0 0```

Commands to get it to work.
```
mkdir /var/lib/kubelet/pods/27153f2b-7664-11e9-95b0-000af7854ba0/volumes/kubernetes.io~local-volume/local-pv-3a82f760
mount -o bind /mnt/disks/disk1 /var/lib/kubelet/pods/27153f2b-7664-11e9-95b0-000af7854ba0/volumes/kubernetes.io~local-volume/local-pv-3a82f760
```

**Comment by cofyc** [comment]
Can you paste the output of `mountpoint /mnt/disks/disk1`?

**Comment by cofyc** [comment]
kubelet should retry to bind `/mnt/disks/disk1` to `/var/lib/kubelet/pods/27153f2b-7664-11e9-95b0-000af7854ba0/volumes/kubernetes.io~local-volume/local-pv-3a82f760`

**Comment by msau42** [comment]
Also, is your kubelet running in a container?

**Comment by hangchan** [comment]
Yes my kubelet is running in a container.

```

**Comment by hangchan** [comment]
Thanks @msau42.  My kubelet was running in a container.

Added additional binds and it's working.

```
        "HostConfig": {
            "Binds": [
                "/mnt/disks/disk1:/mnt/disks/disk1",
                "/mnt/disks/disk2:/mnt/disks/disk2"
            ],
```
