### ISSUE TITLE
Initialization failed for volume

### ISSUE THREAD

**Issue by spencergilbert** [kubernetes-sigs/sig-storage-local-static-provisioner#107]
Error: `MountVolume.NewMounter initialization failed for volume "local-pv-7f70b248" : path "/mnt/local/vol1" does not exist`

I could certainly be doing something pretty silly here but I'm unable to mount volumes anymore. I had tested this earlier in the year and didn't have issues so I'm not sure what I'm missing. I've attached the manifest I used.

[templated_manifest.txt](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/files/3239650/templated_manifest.txt)

**Comment by cofyc** [comment]
The kubelet emitted this error log because the path `/mnt/local/vol1` didn't exist on the node. I guess `/mnt/local/vol1` is the path of local PV used by the pod. You need to check the path on that node.

**Comment by spencergilbert** [comment]
Off the host:
`root@halfling-fidel:~# cd /mnt/local/vol1/
root@halfling-fidel:/mnt/local/vol1# pwd
/mnt/local/vol1`

**Comment by cofyc** [comment]
Is your kubelet running in a container?

**Comment by spencergilbert** [comment]
Ah, yes. We're using Rancher so it is containerized.

**Comment by cofyc** [comment]
If the kubelet is running in a container, it cannot access the host filesystem at the same path. You must adjust `hostDir` to the correct path in the kubelet container. 

For example, if the host filesystem is mounted at `/rootfs` in the kubelet container, you need to set `hostDir` to `/rootfs/mnt/local`.

**Comment by cofyc** [comment]
By the way, you can also add a bind for local volumes in kubelet container. e.g.

```
        "HostConfig": {
            "Binds": [
                "/mnt/local:/mnt/local"
            ],
```

**Comment by spencergilbert** [comment]
I really should have documented all this stuff I did when it worked the first time 🙃 

Thanks @cofyc

**Comment by meyerbro** [comment]
Hey @spencergilbert, how did you solve this? I'm also using rancher and I didn't find a hostDir other than "/" on my case...

**Comment by meyerbro** [comment]
@cofyc, any guess on this one? Thanks!

**Comment by spencergilbert** [comment]
Just as above since the kubelet is dockerized you need to pass additional bind config into the cluster yaml config, i've been matching ie. create pv at /mnt/local on worker node bind config as /mnt/local:/mnt/local

**Comment by cofyc** [comment]
yes, here is rancher docs about how to configure extra binds: https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-binds

**Comment by cornel-masson** [comment]
@cofyc I'm using Rancher Desktop on Windows 10. In which config file must I look for services.kubelet.extra_binds? Or is there another way to configure this in Rancher Desktop?
