### ISSUE TITLE
hack/local-up-cluster.sh in getting-started.md is missing

### ISSUE THREAD

**Issue by v1c77** [kubernetes-sigs/sig-storage-local-static-provisioner#112]
Hi, 
I tried to set up a local test cluster step by step  but I can't find  the related script `hack/local-up-cluster.sh`. 
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blame/master/docs/getting-started.md#L89

**Comment by cofyc** [comment]
hi,

`hack/local-up-cluster.sh` is a script to run Kubernetes on the Linux locally. Full document about it is [here](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md).

I'll update the docs to make it more clearly.
