### ISSUE TITLE
Allow additional labels to be attached to PVs provisioned by the provisioner

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/sig-storage-local-static-provisioner#116]
Ideally, I would like to accurately track PVs that were provisioned by this provisioner so as it can better integrate with higher level tools like - https://github.com/openshift/local-storage-operator

My own use case is:

1. Use creates a CR that triggers DaemonSet managed by provisioner and local-storage-operator.
2. Provisioner daemon provisions PVs as expected.
3. User deletes the CR. At this point, I do not accurately know if it is safe to delete the LocalVolume CR or if there are PVs that are in use and deleting the CR will also delete the daemonsets managed by it and hence those in-use PVs will not be properly cleaned up (may have left over data).

cc @msau42 @cofyc

**Comment by cofyc** [comment]
Yes, I'd like to allow additional labels to be attached to provisioned PVs (xref: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/52#issuecomment-484014519).

For your use case, does `pv.kubernetes.io/provisioned-by` annotation serve your purpose?

**Comment by gnufied** [comment]
@cofyc The `provisioned-by` annotation includes node name(and some random hash?) IIRC. For example:

```
pv.kubernetes.io/provisioned-by: local-volume-provisioner-127.0.0.1-1ab94f1b-ba0b-42db-a0b1-98890017377f
```

^ which won't work for my use case. The other thing obviously is - user may have been directly using local-storage-provisioner whereas I am interested in tracking PVs that are were created by the `LocalVolume` CR.

So yeah I think ability to specify custom labels in configmap should work for my use case. I don't particularly need per-storageclass-configuration labels but same set of labels for all PVs is what I am looking for. I will see if I can open a PR for this.
