### ISSUE TITLE
Feature: periodic check for volume size

### ISSUE THREAD

**Issue by spencergilbert** [kubernetes-sigs/sig-storage-local-static-provisioner#117]
This might be an edge use-case, but we're currently using this provisioner combined with ZFS to manage our PVs. We're able to dynamically resize the "volume" size on the host FS and it could be useful for the provisioner to pick up on those changes.

**Comment by msau42** [comment]
Sounds interesting. We do allow PV size to be modified although it would be interesting to figure out how this interacts with storageclass quota. Cc @gnufied
