### ISSUE TITLE
Migration of local PVs by moving disks

### ISSUE THREAD

**Issue by JohnStrunk** [kubernetes-sigs/sig-storage-local-static-provisioner#127]
**Summary**
It should be possible to move local PVs (w/ data intact) from one host to another by moving the underlying physical devices.

**Motivation**
Providing storage in bare metal environments using physical disks attached to nodes is a significant use case for the local provisioner. If a node becomes inoperable due to HW or SW failure, it should be possible for an admin to physically move the disks from the failed node to a still-functioning one and have the system automatically recognize those existing PVs.

This capability would provide consumers of persistent storage with a recovery method that is potentially faster and more resource efficient than rebuilding many TBs worth of data that has become inaccessible.

*Note: It's not clear to me whether the local provisioner could actually do this, but this seems like a reasonable place to start the discussion.*

**Comment by msau42** [comment]
This may be related to https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/75, where we're exploring better ways to uniquely identify a local PV

**Comment by cofyc** [comment]
It's not possible to migrate local volumes without change of PVs. The `local.path` and `nodeAffinity` fields of persistent volumes are immutable in kube-apiserver. The path and the node on which local volume resides represents a unique local storage resource in the cluster. I think the simple way to migrate local volumes is to delete old PVs and discover it as a new PV on the new node (better to clean data too). Local PVs are expected to use by data replicated system or as local cache. I think trying to persist data in local PVs across nodes is not a good idea.

**Comment by JohnStrunk** [comment]
Implementing this may require kube changes. Perhaps it's worth a discussion w/ the sig to see if others have this use-case.

My concern is that even for replicated data, rebuilding/copying potentially 10+ TB of data onto a new PV is time and resource intensive. It would be much easier to move the disk to a new node and have the app just update with the changes since the failure.

**Comment by msau42** [comment]
I think it can be done today very carefully as a manual process.

Create a new PV to represent the moved disk, prebind it to the PVC.  Recreate PVC and have it bind to the new PV. Restart pod

**Comment by JohnStrunk** [comment]
Good point.
That raises the question that if #75 changes the naming to something generic, would this group be supportive of adding functionality to the provisioner that would automate the PV/PVC switching?

**Comment by msau42** [comment]
I'm not sure how the provisioner can help orchestrate this since there's no central control plane to manage state across nodes.

As a first step, I think it would be good to try out the sequence I suggested, document the steps maybe in our FAQ/best practices section, and then we can think about how to automate it.  At a first glance I'm not sure if the provisioner is the right place. Maybe a script could suffice?
