### ISSUE TITLE
PV definition Helm only

### ISSUE THREAD

**Issue by zrml** [kubernetes-sigs/sig-storage-local-static-provisioner#131]
Hi All:

In the description on how to define a PV I only see a Helm chart option.

See the page at: sig-storage-local-static-provisioner/docs/getting-started.md

No Helm here.
Could somebody point me to an example with a std k8s yml def?
thanks a bunch

**Comment by msau42** [comment]
You can check out the generated examples that we use to test our helm chart:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/master/helm/generated_examples

**Comment by zrml** [comment]
@msau42 Thanks Michelle. Closing it. Saw you at KubeCon EU in May :)
