### ISSUE TITLE
daemonset not created

### ISSUE THREAD

**Issue by AsherShoshan** [kubernetes-sigs/sig-storage-local-static-provisioner#146]
installed on Openshift 4.2 in ns 'local-storage"
kubectl describe daemonset local-volume-provisioner -n local-storage -->
Error creating: pods "local-volume-provisioner-" is forbidden: unable to validate against any security context constraint: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

**Comment by gnufied** [comment]
What instructions did you follow for installing? Openshift-4.2 will ship local-storage-operator as default method of configuring local-storage in the cluster - https://github.com/openshift/local-storage-operator . You can try the operator and open bugs if you see any issues.

**Comment by AsherShoshan** [comment]
Hi,
I haven't installed openshift local-storage provisioner.
only the sig-local-storage provisioner
Probably it's something to do with openshift csc authorizations?

**Comment by msau42** [comment]
@AsherShoshan do you still have issues?

**Comment by AsherShoshan** [comment]
No, Thanks
(openshift cluster)
