### ISSUE TITLE
PV in pending status for ever

### ISSUE THREAD

**Issue by cwpestana** [kubernetes-sigs/sig-storage-local-static-provisioner#147]
Hello,
I'am trying to deploy sig storage in a UCP (Docker EE) enviroment, provisioner pods are deployed and working, but the PV remains in "pending" status. 

Here is the provisioner log:
I0910 13:31:41.208017       1 common.go:334] StorageClass "localstorage" configured with MountDir "/data/rook/storage-dir/sig", HostDir "/data/rook/storage-dir/sig", VolumeMode "Block", FsType "", BlockCleanerCommand ["/scripts/shred.sh" "2"]
I0910 13:31:41.208083       1 main.go:63] Loaded configuration: {StorageClassConfig:map[localstorage:{HostDir:/data/rook/storage-dir/sig MountDir:/data/rook/storage-dir/sig BlockCleanerCommand:[/scripts/shred.sh 2] VolumeMode:Block FsType:}] NodeLabelsForPV:[storage-node] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false LabelsForPV:map[] SetPVOwnerRef:false}
I0910 13:31:41.208105       1 main.go:64] Ready to run...
I0910 13:31:41.208411       1 common.go:396] Creating client using in-cluster config
I0910 13:31:41.405401       1 main.go:85] Starting controller
I0910 13:31:41.405429       1 main.go:101] Starting metrics server at :8080
I0910 13:31:41.405484       1 controller.go:45] Initializing volume cache
I0910 13:31:41.606131       1 controller.go:108] Controller started
I0910 13:31:41.606758       1 discovery.go:331] Found new volume at host path "/data/rook/storage-dir/sig/raw1" with capacity 1073741824, creating Local PV "local-pv-e89480f9", required volumeMode "Block"
I0910 13:31:41.625509       1 discovery.go:366] Created PV "local-pv-e89480f9" for volume at "/data/rook/storage-dir/sig/raw1"
I0910 13:31:41.625480       1 cache.go:55] Added pv "local-pv-e89480f9" to cache
I0910 13:31:41.838575       1 cache.go:64] Updated pv "local-pv-e89480f9" to cache

And the pv describe output:
Name:              local-pv-e89480f9
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by=local-volume-provisioner-wdocker1-1099ef3e-d3a9-11e9-8aee-0242ac110005
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      localstorage
**Status:            Pending**
Claim:             
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Block
Capacity:          1Gi
Node Affinity:     
  Required Terms:  
    Term 0:        kubernetes.io/hostname in [wdocker1]
Message:           
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /data/rook/storage-dir/sig/raw1
Events:    <none>
 
I don't known why is in pending status, I can't find anything in logs

Thanks in advance

**Comment by msau42** [comment]
PV controller in kube-controller-manager is responsible for processing new PVs and setting Phase to Available.  Can you check your kube-controller-manager logs?

**Comment by cwpestana** [comment]
The serviceaccount kube-system:persistent-volume-binder did not have enough permissions in UCP, I assigned the appropriate permissions and the PV was created:
Describe output:

Name:              local-pv-e89480f9
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by=local-volume-provisioner-wdocker1-1099ef3e-d3a9-11e9-8aee-0242ac110005
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      localstorage
**Status:            Available**
Claim:             
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Block
Capacity:          1Gi
Node Affinity:     
  Required Terms:  
    Term 0:        kubernetes.io/hostname in [wdocker1]
Message:           
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /data/rook/storage-dir/sig/raw1
Events:    <none>

But when a statefulset is deployed the PVC remains in "Pending" status
Name:          local-vol-local-test-0
Namespace:     default
StorageClass:  localstorage
**Status:        Pending**
Volume:        
Labels:        app=local-test
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  WaitForFirstConsumer  4m (x2781 over 11h)  persistentvolume-controller  waiting for first consumer to be created before binding

I found this message in kube-controller-manager logs
{Kind:"PersistentVolumeClaim", Namespace:"testlocalstorage", Name:"local-vol-local-test-0", UID:"ca0f7e3d-d3d8-11e9-9742-0242ac110004", APIVersion:"v1", ResourceVersion:"33060468", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding

Here is the statefulset yaml

piVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-test
spec:
  serviceName: "local-service"
  replicas: 1
  selector:
    matchLabels:
      app: local-test
  template:
    metadata:
      labels:
        app: local-test
    spec:
      containers:
      - name: test-container
        image: k8s.gcr.io/busybox
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "sleep 100000"
        volumeMounts:
        - name: local-vol
          mountPath: /usr/test-pod
  volumeClaimTemplates:
  - metadata:
      name: local-vol
     # name: example-local-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "localstorage"
      resources:
        requests:
          storage: 50Mi

Thanks in advance

**Comment by msau42** [comment]
Did Statefulset controller create a pod? And was scheduler able to process it?

**Comment by cwpestana** [comment]
I found the problem, the PVC create has "VolumeMode: Filesystem" but the PV is "VolumeMode: Block", I added "volumeMode: Block" in spec section of the statefulset and the PVC was created with status "bound"
Here the describe output of PVC

Name:          local-vol-local-test-0
Namespace:     testlocalstorage
StorageClass:  localstorage
Status:        Bound
Volume:        local-pv-e89480f9
Labels:        app=local-test
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Block
Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  WaitForFirstConsumer  6m (x203 over 56m)  persistentvolume-controller  waiting for first consumer to be created before binding


Now the pod in unable to mount the volume showing this error:

Unable to mount volumes for pod "local-test-0_testlocalstorage(515eff3e-d531-11e9-b57f-0242ac110004)": timeout expired waiting for volumes to attach or mount for pod "testlocalstorage"/"local-test-0". list of unmounted volumes=[local-vol]. list of unattached volumes=[local-vol default-token-4tkmt]

I looked for errors in controller-manager logs but nothing, here is pod describe output:

Name:               local-test-0
Namespace:          testlocalstorage
Priority:           0
PriorityClassName:  <none>
Node:               wdocker1/x.x.x.x
Start Time:         Thu, 12 Sep 2019 09:45:42 +0200
Labels:             app=local-test
                    controller-revision-hash=local-test-6849b4fb99
                    statefulset.kubernetes.io/pod-name=local-test-0
Annotations:        kubernetes.io/psp=privileged
Status:             Pending
IP:                 
Controlled By:      StatefulSet/local-test
Containers:
  test-container:
    Container ID:  
    Image:         k8s.gcr.io/busybox
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      sleep 100000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/test-pod from local-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4tkmt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  local-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  local-vol-local-test-0
    ReadOnly:   false
  default-token-4tkmt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4tkmt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     com.docker.ucp.manager
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age               From                                 Message
  ----     ------       ----              ----                                 -------
  Normal   Scheduled    9m                default-scheduler                    Successfully assigned testlocalstorage/local-test-0 to bmewdocker1.mercados.local
  Warning  FailedMount  48s (x4 over 7m)  kubelet, bmewdocker1.mercados.local  Unable to mount volumes for pod "local-test-0_testlocalstorage(515eff3e-d531-11e9-b57f-0242ac110004)": timeout expired waiting for volumes to attach or mount for pod "testlocalstorage"/"local-test-0". list of unmounted volumes=[local-vol]. list of unattached volumes=[local-vol default-token-4tkmt]
