### ISSUE TITLE
How to prevent a local PV claim from binding to the 'Wrong' local PV (volume size way exceeds what was requested) 

### ISSUE THREAD

**Issue by kcao3** [kubernetes-sigs/sig-storage-local-static-provisioner#150]
Hello. I'm currently using this sig-storage-local-static-provisioner and have 2 local PVs: one is 10GiB and the other one is 1TiB in my k8s cluster. If a developer creates a 1GiB PV claim, does anyone how a technique to ensure this PV claim is always binding to the 10GiB PV rather than the 1TiB PV?

My current workaround is to delete the sig-storage-local-static-provisioner DaemonSet and the very large PV before the PV claim is created. Once the PV claim is bound to the correct PV, I then relaunch the sig-storage-local-static-provisioner DaemonSet, which then re-create  the very large PV.  This is such a pain and I hope there's a better way to prevent the claim from binding to the 'WRONG' PV.  Anyone?

**Comment by kcao3** [comment]
> Hi all. I'm currently using the sig-storage-local-static-provisioner from <https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner> and have 2 local PVs: one is 10GiB and the other one is 1TiB. If I create a 5GiB PVC, does anyone how to ensure this PV claim is always binding to the 10GiB PV rather than the 1TiB PV?
<sub>[View in Slack](https://kubernetes.slack.com/archives/C09QZFCE5/p1569938038169600)</sub>

**Comment by msau42** [comment]
My suggestion is to put your PVs in different StorageClasses, since it sounds like they're intended for different workloads.

https://github.com/kubernetes/kubernetes/issues/83323 can help with this by preferring nodes closer to the PV size, but it won't completely help based off of other scheduler priorities.

**Comment by msau42** [comment]
/close

We can track the priority function implementation through kubernetes/kubernetes#83323
