### ISSUE TITLE
When using Retain policy. When recreating a PVC with same name The previous one is not reused

### ISSUE THREAD

**Issue by fberzolla** [kubernetes-sigs/sig-storage-local-static-provisioner#151]
Hi
I'm using the provider with a storage class with Retain policy. It works fine for the first PVC. 
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/1150702/65988074-72d83280-e487-11e9-97d3-f1eb56f4c2b1.png">
But if i delete the PVC and recreate it the previous associated PVC is not re-used (Retain)
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1150702/65988316-e1b58b80-e487-11e9-95dc-df07e2fd1635.png">

Is there a way to re-use the previously deleted PVC with the same name ?

Thanks

**Comment by bcollard** [comment]
Hello,

What do you want to prove?

When you delete a PVC, the _associated_ PV is **released** if the **reclaim policy** associated to the **storageClass** is set to "**Retain**".

That permits an admin to perform additional steps, such as data backup.

But, from my understanding [of the doc](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim), the goal is not to make this same PV **Available** again. Anyway, the PV contains a claimRef somewhere in its description, referencing the UUID of the old PVC.

My understanding is that once reclaimed, a PV has to be deleted (and optionally recreated).

So with this "**Retain**" policy, the underlying volume plugin or "provider", here  "**local**" (i.e. YOU as a sysadmin) is in charge of actually deleting the data, or keeping it safe. I'm not sure that the static-provisioner won't perform any erase script btw.

Then you can manually delete the PV.
Once deleted, the "local-static-provider" should recreate another one automatically (directory exists but no associated PV) ... but with a different name! see:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/93915e330be4291f209b13dc6df063729bd4d9c4/pkg/discovery/discovery.go#L365

So, I'm not sure that you test consisting of deleting some PVC is relevant. The controller of your application (deploy, sts, ds, etc.) is in charge of recreating pods if they ever fail and they should be able to reuse the same PVC.

**Comment by msau42** [comment]
@bcollard is correct in that in the normal scenario, to reuse the PV, it should be cleaned up (data wiped), and then PV object deleted. 

In your case, do you want to keep the data and reuse it for the new application that uses the same PVC name + namespace?  If so, then you can patch the PV to remove the PV.Spec.ClaimRef.UID field. That should allow it to rebind to another PVC with the same name/namespace (but different uid).

> Once deleted, the "local-static-provider" should recreate another one automatically (directory exists but no associated PV)

Assuming the mount name is the same after recreation, then the pv name should actually be the same. It uses file name + storageclass + nodename as inputs to the hash.
