### ISSUE TITLE
btrfs support 

### ISSUE THREAD

**Issue by R-omk** [kubernetes-sigs/sig-storage-local-static-provisioner#156]
What do you think about integration with btrfs?

btrfs supports snapshots and quotas, it is also easy to backup and migrate to another host. There is also RAID support

**Comment by cofyc** [comment]
hi, sorry for missing this
I do not fully understand your suggestion. local volume static provisioner discoveries volumes on the node, which filesystem the volume is up to the user. Can you describe a use case?

**Comment by R-omk** [comment]
it's about dynamically creating partitions (subvolume in the case of btrfs or logical volume in lvm).
Like here (https://github.com/rancher/local-path-provisioner)  subdirectories are dynamically created
