### ISSUE TITLE
Configuration of volume mode "block" should be completed

### ISSUE THREAD

**Issue by lz006** [kubernetes-sigs/sig-storage-local-static-provisioner#159]
In order to get local-provisioner creating pvs for raw block devices host path "/dev" needs to be mounted in daemonset to "/dev" as well.

This hasn't been described in docs nor an example is provided. 

Furthermore this might has led to error in kubespray https://github.com/kubernetes-sigs/kubespray/issues/5389

**Comment by cofyc** [comment]
it's not documented, but builtin in helm chart. do you suggest to document it, can you send a PR?

**Comment by Kartik494** [comment]
I would like to give a try on this.
/assign

**Comment by Kartik494** [comment]
@cofyc raised a PR here https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/341 . Please take a look
Thanks!!
