### ISSUE TITLE
Provision volume using mount path

### ISSUE THREAD

**Issue by kapil-ms** [kubernetes-sigs/sig-storage-local-static-provisioner#175]
Hi

I am trying to create a persistent volume for a local disk /dev/sdb1 mounted at /mnt in an Azure Kubernetes Service cluster. I get an error as below-

```
I0219 01:07:19.128192       1 main.go:64] Ready to run...
I0219 01:07:19.128513       1 common.go:396] Creating client using in-cluster config
I0219 01:07:19.158997       1 main.go:85] Starting controller
I0219 01:07:19.159020       1 main.go:101] Starting metrics server at :8080
I0219 01:07:19.159218       1 controller.go:45] Initializing volume cache
I0219 01:07:19.360655       1 controller.go:108] Controller started
E0219 01:07:19.361030       1 discovery.go:250] Skipping file "/mnt/DATALOSS_WARNING_README.txt": not a directory nor block device
E0219 01:07:19.361069       1 discovery.go:301] Path "/mnt/lost+found" is not an actual mountpoint
```

As per my understanding from the documentation, the local static provisioner requires the mount points as links in a directory through which it loops. But that requires an additional step. 

Is there a way to create a persistent volume by specifying the mount path in the configuration for the local static provisioner ? In the AKS cluster, I have noticed that the local disk is always mounted at /mnt.

Thanks

**Comment by cofyc** [comment]
no, it requires the directory is a mount point, this is why it fails with this error:

```
E0219 01:07:19.361069       1 discovery.go:301] Path "/mnt/lost+found" is not an actual mountpoint
```

I didn't use Azure Kubernetes Service yet. Is there a local disk mounted at `/mnt` and you want to discover it as a local volume? 

First, you need to create a discovery directory other than `/mnt` for local volume provisioner, e.g. `/local-disks`.

Then, get the UUID of the device and make it accessible in the discovery directory: 

```
blkid /dev/sdb1
```

link it into the discovery directory or bind mount it:

```
mkdir /local-disks/<uid-from-blkid-command>
ln -s /mnt /local-disks/<uid-from-blkid-command>
```

or

```
mkdir /local-disks/<uid-from-blkid-command>
mount --bind /mnt /local-disks/<uid-from-blkid-command>
```

**Comment by kapil-ms** [comment]
This is what the disk space on the node looks like-
![image](https://user-images.githubusercontent.com/20193720/74799710-1c2c9300-5286-11ea-89f2-3e7a1f83151b.png)

/dev/sdb1 is an ext4 formatted disk mounted at path /mnt. It has a file and a directory in it by default.
![image](https://user-images.githubusercontent.com/20193720/74799752-50a04f00-5286-11ea-8973-5a8447399745.png)

I want to discover ONLY this disk as a local persistent volume.

I tried setting hostDir to "/" which discovers 3 volumes-
/mnt
/dev
/run

```
data:
  storageClassMap: |
    fast-disks:
       hostDir: /
       mountDir: /mydisks
       volumeMode: Filesystem
       fsType: ext4
```

1. /dev and /run are not of type ext4. I thought the provisioner might filter based on the value of `fsType`. Is that possible ?

2. Why were other entries from `df -Th` not recognized as a volume ?

3. I would like to avoid the steps you've mentioned since they will have to be run whenever I scale the cluster and add more nodes. Is there a way to automate this or not require these steps at all ?

**Comment by cofyc** [comment]
hi, you can automate this via init container. https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

use `/` as a discovery directory is not recommended. If it is possible to change the mount point of the local disk, you can change it to some other place, like `/mnt/local`. Then you can use `/local` as discovery directory.

**Comment by kapil-ms** [comment]
So, I have the following setup.

1. I have an init container which creates a link as follows-
```
DISK_UUID=$(blkid -s UUID -o value /dev/sdb1) 
ln -s /dev/disk/by-uuid/$DISK_UUID /mnt/disk
```

2. The storage class map looks like-
```
storageClassMap: |
    fast-disks:
       hostDir: /mnt/disk
       mountDir: /mnt/disk
       blockCleanerCommand:
         - "/scripts/quick_reset.sh"
       volumeMode: Filesystem
       fsType: ext4
```

The PV gets created and when a pod requests for the volume, the PVC gets created. However, when the pod and PVC are deleted, I get the following error in the local static provisioner-

```
I0222 01:16:46.621216       1 deleter.go:275] Deleting PV block volume "local-pv-4983a294" device hostpath "/mnt/disk/f49c22a2-fed0-4790-8b63-b4ee90b3dbd3", mountpath "/mnt/disk/f49c22a2-fed0-4790-8b63-b4ee90b3dbd3"
I0222 01:16:46.624067       1 deleter.go:305] Cleanup pv "local-pv-4983a294": StdoutBuf - "Calling mkfs"
I0222 01:16:46.626101       1 deleter.go:319] Cleanup pv "local-pv-4983a294": StderrBuf - "mke2fs 1.43.4 (31-Jan-2017)"
I0222 01:16:46.626393       1 deleter.go:319] Cleanup pv "local-pv-4983a294": StderrBuf - "/mnt/disk/f49c22a2-fed0-4790-8b63-b4ee90b3dbd3 is mounted; will not make a filesystem here!"
E0222 01:16:46.626667       1 deleter.go:280] exit status 1
E0222 01:16:46.626687       1 deleter.go:232] exit status 1
I0222 01:16:56.621685       1 deleter.go:193] Cleanup for pv local-pv-4983a294 failed. Restarting cleanup
```

I think this could be happening because in an Azure Linux VM, `/dev/sdb1` is already mounted at `/mnt`. I linked it to a subfolder since the provisioner requires a discovery directory.

Any way to prevent this error from happening or another way to achieve this use case ?

**Comment by andyzhangx** [comment]
@kapil-ms pls try with this solution on AKS:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/local

And you could run following command to discover (`/dev/sdb1`) disk
```console
kubectl apply -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/local/local-pv-provisioner-tempdisk.yaml
```
