### ISSUE TITLE
Could not get node information: does not work with K8s version 1.15.7

### ISSUE THREAD

**Issue by kapil-ms** [kubernetes-sigs/sig-storage-local-static-provisioner#176]
Hi

After deploying the generated yaml to an Azure Kubernetes service cluster with Kubernetes v1.15.7, I get the following error in the provisioner pods-

```
F0219 00:14:24.757421 1 main.go:130] Could not get node information: Get https://10.0.0.1:443/api/v1/nodes/aks-nodepool1-26850923-vmss000001: dial tcp 10.0.0.1:443: i/o timeout
```

However, the pods are able to get the node information when I deployed the same generated yaml in a cluster with kubernetes v1.14.7.

Could you please help with this issue?

Thanks

**Comment by cofyc** [comment]
can you paste the generated yaml here?

**Comment by kapil-ms** [comment]
I ended up recreating a cluster with v1.15.7 to verify and it worked. So maybe something was wrong with that particular cluster.
