### ISSUE TITLE
Could not get specified capacity for local PV

### ISSUE THREAD

**Issue by yustoris** [kubernetes-sigs/sig-storage-local-static-provisioner#180]
I've applied the provisioner like following (except RBAC settings) on a RKE (k8s version is 1.14.6).
https://gist.github.com/yustoris/28f0c025e2cbf0ccdcbb7a5bb84f3acc#file-provisioner-yaml

And got provisioner log below that seems successfully created PV.
https://gist.github.com/yustoris/28f0c025e2cbf0ccdcbb7a5bb84f3acc#file-provisioner-log

However, when I applied a [test application manifest and PVC](https://gist.github.com/yustoris/28f0c025e2cbf0ccdcbb7a5bb84f3acc#file-app-yaml), I realized that the pod container of the app does not have the specified capacity (I specified 200Gi in the PVC, but I just got 16GB, mounted on `/mnt/pv` , see the container log below ).

```
root@persistent-deployment-6d7cd5759b-vhpnm:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         181G   18G  163G  10% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda4       181G   18G  163G  10% /etc/hosts
devtmpfs         16G     0   16G   0% /mnt/pv
shm              64M     0   64M   0% /dev/shm
tmpfs            16G   12K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
```

Could you tell me how to investigate the reason of this capacity mismatch and to resolve it ?

**Comment by cofyc** [comment]
maybe the path of local PV points to the wrong filesystem. what's the capacity in the PV object? haven't you check the mount point of local PV on the node?
