### ISSUE TITLE
nodeLabelsForPV should contain kubernetes.io/hostname by default

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/sig-storage-local-static-provisioner#186]
I came here to submit a patch to add this label to PVs, but on reviewing the code I discovered there's already an option to do it, but it's disabled by default.

The host node of local storage which can only be accessed from its host node is such a fundamental property that I was extremely surprised to discover it was not already discoverable. My specific use case is that I need to select a PV on a specific node on order to make scheduling sane, and WaitForFirstConsumer doesn't help me for an uninteresting chain of reasons.

The real use case here is: why wouldn't you just include it? There are a ton of potential reasons you might want to easily see which node a PV is attached to, or select a set of PVs based on node, and it's super cheap to add up front.

On the flip side, discovering the existence of nodeLabelsForPV took me several hours of RTFS[1], I still have to work out how to apply it, and I'm pretty sure I can't use it to retrospectively update my PVs, so I have to delete them all anyway.

[1] I subsequently discovered it is mentioned in provisioner.md, complete with this specific example! I didn't look there first primarily because I don't know it could be configured. I'm a real-world user :)

**Comment by cofyc** [comment]
add `kubernetes.io/hostname` label by default in the next major release? cc @msau42
