### ISSUE TITLE
use helm template generate syntax error provisioner yaml file

### ISSUE THREAD

**Issue by vistamin** [kubernetes-sigs/sig-storage-local-static-provisioner#197]
**What happened**: the provisioner pod can not running

**What you expected to happen**: use example provisioner file is ok, but use custom provisioner file failed to run pods.

**How to reproduce it**: 

1. helm template ./helm/provisioner --values custom-values.yaml > deployment/kubernetes/provisioner_generated.yaml
2. the namePattern in ConfigMap is \*, but you should use double quote to enclosed it, like "*", else
the CrashLoopBackOff pod log is like 
F0603 09:39:31.680558       1 main.go:61] Error parsing Provisioner's configuration: &errors.errorString{s:"fail to Unmarshal yaml due to: &errors.errorString{s:\"error converting YAML to JSON: yaml: line 10: did not find expected alphabetic or numeric character\"}"}. Exiting...

**Anything else we need to know?**:
I found update helm/provisioner/templates/configmap.yaml can resolve it, diff is
\-       namePattern: {{ $classConfig.namePattern }}
\+      namePattern: "{{ $classConfig.namePattern }}"

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
- Others:

**Comment by cofyc** [comment]
Thanks for reporting this! can you send a PR to fix it?

**Comment by cofyc** [comment]
closed via https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/198
