### ISSUE TITLE
Recover workloads using local PVs from data loss in the cloud

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#202]
This is the track issue for some related problems in the cloud when the node is permanently deleted.

I'm thinking about writing a cloud controller to automate the recovery process. Here is the proposal: https://docs.google.com/document/d/1SA9epEwA3jPwibRV0ccQwJ2UfZXoeUYKyNxNegt0vn4

related issues:

- https://github.com/kubernetes/kubernetes/issues/78756
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/201
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/181

**Comment by cdenneen** [comment]
@cofyc any further work past the initial proposal?
/help
/kind feature

**Comment by arianvp** [comment]
Wouldn't it already be enough as a first approximation to simply respect `--pod-eviction-timeout` as pased to `kube-controller-manager` ?

Just like pods get evicted after `--pod-eviction-timeout` after a node goes to `Ready=Unknown` or `Ready=False`, we can evict the `PVC` if the node is down that long.

If that timeout is good enough to try and evict the pod; then it's good enough to try and evict the PVC; is it not?

It does not handle the cases of  node reboots losing data (e.g. in GKE and EKS) but it does handle the case of "Node permanently gone" both on on-prem and on managed services where each new spawned node gets a new name (E.g. EKS)

**Comment by mattcary** [comment]
Update! We will be having a summer intern doing some work on this. We'll post more updates here as the project comes together.  

We may not organize kubernetes-sigs membership for the intern so the actual PR upstream may be indirected through another member of my team. Just fair warning.
