### ISSUE TITLE
Provisioner is trying to recreate existing volumes

### ISSUE THREAD

**Issue by johny-mnemonic** [kubernetes-sigs/sig-storage-local-static-provisioner#209]
**What happened**:
Provisioner is creating volumes for us just fine, but after using it for some time, we noticed, that it's logs are full of following kind of messages:
`I0720 20:23:35.289358       1 discovery.go:384] Found new volume at host path "/mnt/disks/minio_pv-0" with capacity 5388179521536, creating Local PV "local-pv-e24d9ea6", required volumeMode "Filesystem"
I0720 20:23:35.294675       1 discovery.go:384] Found new volume at host path "/mnt/disks/minio_pv-1" with capacity 5388179521536, creating Local PV "local-pv-8e4a6353",  required volumeMode "Filesystem"
E0720 20:23:35.299447       1 discovery.go:220] Failed to discover local volumes: 2 error(s) while discovering volumes: [error creating PV "local-pv-e24d9ea6" for volume at "/mnt/disks/minio_pv-0": persistentvolumes "local-pv-e24d9ea6" already exists error creating PV "local-pv-8e4a6353" for volume at "/mnt/disks/minio_pv-1": persistentvolumes "local-pv-8e4a6353" already exists]`

Everytime it runs (i.e. every 10s) it is trying to create volumes which are already created and used :-O

**What you expected to happen**:
We expected it will create volumes only once we add new device/folder into /mnt/disks.

**How to reproduce it**:
We are using folder _/mnt/disks_ for local volumes and we bind mount actual folders or devices to it's subdirectories.
In the example above, _/mnt/disks/minio_pv-0_ is bind mounted to a folder on different physical disk/device, but we are seeing the same issue also with bind mounts to a folder on the same device as _/mnt/disks_.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): CentOS 7.7
- Kernel (e.g. `uname -a`): 5.4.42-1.el7.gdc.x86_64
- Install tools:
- Others:

**Comment by cofyc** [comment]
Have you recreated the node object?

**Comment by cofyc** [comment]
if you changed the node UID (e.g. recreating the node object),  provisioner running on this node will use a new provisioner name (by default, provisioner name is `local-volume-provisioner-<node-name>-<node-uid>`) and try to discover local volumes using this new name again.

The creation will fail because the name of the PV exists.

**Comment by johny-mnemonic** [comment]
> if you changed the node UID (e.g. recreating the node object), provisioner running on this node will use a new provisioner name (by default, provisioner name is `local-volume-provisioner-<node-name>-<node-uid>`) and try to discover local volumes using this new name again.
> 
> The creation will fail because the name of the PV exists.

Yep, as we have Kubernetes in cloud, we do redeploy the nodes quite often, which includes deleting the node definition and then spinning up the new node. Some of the nodes do have persistent disks, so the volumes are kept intact.

What do you recommend in this case? Should we also drop PVC and PV definition while deleting the node and then let it create the volumes again?

**Comment by cofyc** [comment]
You can set `useNodeNameOnly` to `true` in the configuration. See https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/provisioner.md#configuration

Then, the UID will not be used as part of the provisioner name. 

Note that, after changing this configuration, you must update the existing PVs by removing the UID part from the `pv.kubernetes.io/provisioned-by` annotation. Otherwise, exiting PVs will not be recycled by the provisioner with the new name.

**Comment by johny-mnemonic** [comment]
Thanks! It seems to be working fine.
I have one last question though: Is it possible to fix/edit already existing volume definitions, or do we need to re-create all volumes with the new settings active?

**Comment by cofyc** [comment]
> Thanks! It seems to be working fine.
> I have one last question though: Is it possible to fix/edit already existing volume definitions, or do we need to re-create all volumes with the new settings active?
> 
> Edit: I just noticed you mentioned removing UID in `pv.kubernetes.io/provisioned-by` annotation. Sorry, that I missed it.
> But it looks like the PVs created on nodes, where the new config is applied are still created with the UID in the annotation.
> It is weird though, as I redeployed one node to verify that volumes now survive node redeploy without producing provisioner errors and on that node, the volume doesn't have UID in the annotation now, while it has it before node redeploy :-O

sorry, I forgot to tell you that existing provisioner pods must be restarted to load the new configuration (delete them and with for the damonset controller to recreate) 

(it's the limitation of the current provisioner, may be resolved in 3.0.0 https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/12)

**Comment by johny-mnemonic** [comment]
@cofyc Yeah, I just wanted to write I have found that it doesn't reload the config map :-D
Thanks. I have subscribed that linked issue.

**Comment by gdubicki** [comment]
I know it's an old issue, but maybe someone will follow it like me today in the future, so I'll leave a warning here:

**Doing what's described in [this comment](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/209#issuecomment-662781023) may lead to permanent deletion of your data from the affected volume(s).**

I don't yet know what's the right way to do it, if I learn then I will share it here.
