### ISSUE TITLE
Reducing local-volume-provisioner log verbosity 

### ISSUE THREAD

**Issue by amrmahdi** [kubernetes-sigs/sig-storage-local-static-provisioner#216]
**Is your feature request related to a problem?/Why is this needed**

I'm using container image `mcr.microsoft.com/k8s/local-volume-provisioner:v2.3.5-alpha1` and it is producing a lot of info logs that should probably be debug/trace. See attached logs in just a few minutes.

I'd like to be able to lower the verbosity of this container.

[container.log](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/files/5121789/container.log)

**Describe the solution you'd like in detail**

Be able to tune the log level using an arg/env variable. 

Also the attached log seems like a good candidate for debug/trace levels, not info.

**Describe alternatives you've considered**

I tried setting the `-v` arg with various levels, but still got the same output. 

**Additional context**

Excessive logs translates to more costs storing these logs, so would like to be able to reduce the logs as needed.

@andyzhangx

**Comment by andyzhangx** [comment]
@cofyc do you know how to set the log level in this local volume provisioner? thanks.

**Comment by msau42** [comment]
Most of the code is calling `klog.Infof` without any level. I think we'll need to add some levels to the messages

/remove-lifecycle stale 
/help

**Comment by hellogdc** [comment]
@amrmahdi 
hello, I have read your container.log, find that most of logs are "discovery.go:287] file(tty17) under(/dev) does not match pattern(nvme0n*)". Then i look at the code, find that it uses klog.Infof to  print log, looks like not reasonable. I will try to submmit a pr changing it to "klog.V(4).Infof".
