### ISSUE TITLE
pod Pending

### ISSUE THREAD

**Issue by FrelDX** [kubernetes-sigs/sig-storage-local-static-provisioner#217]
I follow the document https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md#option -1-using-the-local-volume-static-provider creates a local kubenrets cluster for testing. SC is referenced in PVC and pod is always pending

[root@kubernetes01 tmp]# kubectl describe pod redis1-5c646fd686-79p7r
Name:           redis1-5c646fd686-79p7r
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=redis1
                pod-template-hash=5c646fd686
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/redis1-5c646fd686
Containers:
  redis1:
    Image:        redis:6
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /data from redis1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7vmcm (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  redis1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redis1
    ReadOnly:   false
  default-token-7vmcm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7vmcm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't find available persistent volumes to bind.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't find available persistent volumes to bind.
[root@kubernetes01 tmp]#

**Comment by FrelDX** [comment]
this is my yaml file
[root@kubernetes01 tmp]# cat redis/redis.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Block
  storageClassName: fast-disks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis1
  template:
    metadata:
     labels:
       app: redis1
    spec:
     containers:
     - name: redis1
       image: redis:6
       volumeMounts:
       - name: redis1
         mountPath: "/data"
     volumes:
     - name: redis1
       persistentVolumeClaim: 
         claimName: redis1
---
apiVersion: v1
kind: Service
metadata:         
  name: redis1
spec:
  selector:
    app: redis1
  ports:
  - protocol: TCP
    port: 6379 
    targetPort: 6379
  type: NodePort

**Comment by FrelDX** [comment]
[root@kubernetes01 tmp]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                          STORAGECLASS   REASON   AGE
local-pv-32c75bfd                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-3e981376                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-5c869a08                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-734e1af7                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-89d6d312                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-94000bf                           3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-9426baa3                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-95f8bb91                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
local-pv-d2ed2240                          3910Mi     RWO            Delete           Available                                  fast-disks              10m
pvc-055e4028-4696-42b0-9554-da724e196771   1Gi        RWX            Delete           Bound       default/datadir-kafka-0        statefu-nfs             13d
pvc-1ace3f89-04a3-4d6a-a5d1-1acd67cf07dd   1Gi        RWX            Delete           Bound       default/datadir-zk-1           statefu-nfs             13d
pvc-22ec368b-e799-46c4-9f1a-b4696263cecf   10Gi       RWX            Delete           Bound       default/redis                  statefu-nfs             10d
pvc-28dfc24a-5719-43d1-8241-9fe606724fe2   1Gi        RWX            Delete           Bound       default/pgdata-patronidemo-0   statefu-nfs             14d
pvc-994b3cc6-3662-46dc-97dd-569f1e61c2af   1Gi        RWX            Delete           Bound       default/datadir-kafka-1        statefu-nfs             13d
pvc-9a2683a6-d5a8-4e14-be97-24aa9dae3658   1Gi        RWX            Delete           Bound       default/datadir-zk-0           statefu-nfs             13d
pvc-a21c8bcd-15cf-495d-939b-4f8e3b626ea5   1Gi        RWX            Delete           Bound       default/datadir-kafka-2        statefu-nfs             13d
pvc-ac68d536-8e4d-4763-a150-6696fcc84284   1Gi        RWX            Delete           Bound       default/pgdata-patronidemo-1   statefu-nfs             14d
pvc-cfc45fb5-7724-4911-b179-9a4486d4305c   1Gi        RWX            Delete           Bound       default/pgdata-patronidemo-2   statefu-nfs             14d
pvc-e56c228c-e1e0-423b-b829-49d4ced5033e   1Gi        RWX            Delete           Bound       default/datadir-zk-2           statefu-nfs             13d
pvc-f5cac9ed-59b8-41a4-bc5e-580a397a59dd   10Gi       RWX            Delete           Bound       default/fileproxy              statefu-nfs             2d20h
[root@kubernetes01 tmp]# kubectl get sc
NAME          PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
fast-disks    kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  10m
statefu-nfs   nfs-deploy                     Retain          Immediate              true                   20d
[root@kubernetes01 tmp]# kubectl get pvc
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-kafka-0        Bound     pvc-055e4028-4696-42b0-9554-da724e196771   1Gi        RWX            statefu-nfs    13d
datadir-kafka-1        Bound     pvc-994b3cc6-3662-46dc-97dd-569f1e61c2af   1Gi        RWX            statefu-nfs    13d
datadir-kafka-2        Bound     pvc-a21c8bcd-15cf-495d-939b-4f8e3b626ea5   1Gi        RWX            statefu-nfs    13d
datadir-zk-0           Bound     pvc-9a2683a6-d5a8-4e14-be97-24aa9dae3658   1Gi        RWX            statefu-nfs    13d
datadir-zk-1           Bound     pvc-1ace3f89-04a3-4d6a-a5d1-1acd67cf07dd   1Gi        RWX            statefu-nfs    13d
datadir-zk-2           Bound     pvc-e56c228c-e1e0-423b-b829-49d4ced5033e   1Gi        RWX            statefu-nfs    13d
fileproxy              Bound     pvc-f5cac9ed-59b8-41a4-bc5e-580a397a59dd   10Gi       RWX            statefu-nfs    2d20h
pgdata-patronidemo-0   Bound     pvc-28dfc24a-5719-43d1-8241-9fe606724fe2   1Gi        RWX            statefu-nfs    14d
pgdata-patronidemo-1   Bound     pvc-ac68d536-8e4d-4763-a150-6696fcc84284   1Gi        RWX            statefu-nfs    14d
pgdata-patronidemo-2   Bound     pvc-cfc45fb5-7724-4911-b179-9a4486d4305c   1Gi        RWX            statefu-nfs    14d
redis                  Bound     pvc-22ec368b-e799-46c4-9f1a-b4696263cecf   10Gi       RWX            statefu-nfs    10d
redis1                 Pending                                                                        fast-disks     8m12s
[root@kubernetes01 tmp]#

**Comment by tomsucho** [comment]
looks like you have PVs smaller than what the PVC needs i.e.:
```
local-pv-32c75bfd 3910Mi RWO Delete Available fast-disks 10m
local-pv-3e981376 3910Mi RWO Delete Available fast-disks 10m
local-pv-5c869a08 3910Mi RWO Delete Available fast-disks 10m
local-pv-734e1af7 3910Mi RWO Delete Available fast-disks 10m
local-pv-89d6d312 3910Mi RWO Delete Available fast-disks 10m
local-pv-94000bf 3910Mi RWO Delete Available fast-disks 10m
local-pv-9426baa3 3910Mi RWO Delete Available fast-disks 10m
local-pv-95f8bb91 3910Mi RWO Delete Available fast-disks 10m
local-pv-d2ed2240 3910Mi RWO Delete Available fast-disks 10m
```
so that's around 4G while the PVC requests 5Gi?
