### ISSUE TITLE
release 2.4.0

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#223]

**Comment by skaegi** [comment]
Hi @cofyc, is there a plan to do a new release. It would be good to switch off of using canary ;)

Are there any issues you feel need to be resolved before doing a release?

**Comment by cofyc** [comment]
@skaegi sorry for the delay, v2.4.0 is ready now: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.4.0
