### ISSUE TITLE
Update Klog to V2

### ISSUE THREAD

**Issue by Kartik494** [kubernetes-sigs/sig-storage-local-static-provisioner#233]
**What happened**:

I have a query regarding dependency update of klog. This repo is using Klog v1 should we update this to use Klog latest version Klog v2 here? Could you let me know is there any dependency conflict while upgrading this to klog v2
 
**What you expected to happen**:

Update the Klog dependency to use V2 instead

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release): NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Kartik494** [comment]
Could you let me know if it is ok to update the dependency to klog v2. If this is valid i would like to work on this.
Thanks

/assign

**Comment by cofyc** [comment]
> Could you let me know if it is ok to update the dependency to klog v2. If this is valid i would like to work on this.
> Thanks
> 
> /assign

sure, go ahead!

**Comment by Kartik494** [comment]
Thanks @cofyc for clarifying i am working on it and will raise a PR
