### ISSUE TITLE
PVs not created after starting and the provisioner and pods that use local storage

### ISSUE THREAD

**Issue by GururajM** [kubernetes-sigs/sig-storage-local-static-provisioner#243]
Hi,

I'm trying to use static provisioner to manage the volumes and have installed the provisioner in my Kubernetes cluster from the example values.yaml and baremetal-default-storage.yaml. I've 5 worker nodes in my cluster and I can see that the provisioner config has started 5 pods for each of my worker nodes. Now when I start my pods with storage class as "local-storage" and type "persistent-claim", the pod status is pending as no PVs get created and bound to the pods. 

I assumed that the provisioner creates PVs for pods in the nodes being monitored by the provisioner. Any hints with how configure the provisioner and pods to have storage assigned is greatly appreciated. p.s. Kubernetes version is 1.18.

**Comment by msau42** [comment]
This project is not a dynamic provisioner. What it does is discover mount points/disks under the configured directories and creates PVs for each mount point/disk.

So you need to do some pre-work and prepare the disks and mount/symlink them into the directory. See https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/operations.md#prepare-and-set-up-local-volumes-in-discovery-directory for examples on how to prepare the disks.
