### ISSUE TITLE
Is it necessary to custom the period  of discovery local volume ?

### ISSUE THREAD

**Issue by dabaooline** [kubernetes-sigs/sig-storage-local-static-provisioner#260]
**Is your feature request related to a problem?/Why is this needed**
For some usage sence, we may need slow/fast frequence to  discover block/mountPoint.

**Describe the solution you'd like in detail**
Add a flag " --discovery-period "

For detail: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/pkg/controller/controller.go#L115

**Comment by dabaooline** [comment]
Hi @cofyc What is your opinion?

**Comment by cofyc** [comment]
it makes sense, can you add a config for this?

**Comment by dabaooline** [comment]
> it makes sense, can you add a config for this?

ok,my pleasure.
