### ISSUE TITLE
Migrate all e2e tests from k/k repo

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#28]
- [x] copy all local volume provisioner e2e tests from k/k repo (#31)
- [x] clean up local provisioner e2e tests in k/k repo (https://github.com/kubernetes/kubernetes/pull/72617)

/assign

e2e tests from k/k repo:

- [x] Local volume provisioner [Serial] should create and recreate local persistent volume
- [x] Local volume provisioner [Serial] should not create local persistent volume for filesystem volume that was not bind mounted
- [x] Local volume provisioner [Serial] should discover dynamically created local persistent volume mountpoint in discovery directory
- [x] Stress with local volume provisioner [Serial] should use be able to process many pods and reuse local volumes (done in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/31)

**Comment by cofyc** [comment]
@msau42 After all e2e tests are migrated here, should we configure some periodical jobs for different kubernetes versions and different providers (e.g. gke) and testgrid?
xref: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/3307781d7c33f8a69333710f7500d8158e7112a8/README.md#view-ci-results

**Comment by msau42** [comment]
Yup once we have the jobs running, then we can remove the k/k ones
