### ISSUE TITLE
k8s.gcr.io/sig-storage/local-volume-provisioner:v2.5.1 is missing

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/sig-storage-local-static-provisioner#282]
**What happened**:
where is the release image v2.5.1 published? 
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/provisioner-2.5.1

could not find it with `k8s.gcr.io/sig-storage/local-volume-provisioner:v2.5.1`

cc @cofyc

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
btw, it's better mention the major feature & bug fixes between v2.4.0 and v2.5.1 in release notes: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/provisioner-2.5.1

**Comment by andyzhangx** [comment]
@cofyc could you rename or add a new tag(`v2.5.1`) identical to https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/provisioner-2.5.1, we cannot use tag `provisioner-2.5.1`, thanks.

**Comment by cofyc** [comment]
sorry, I'll fix it today.

**Comment by andyzhangx** [comment]
the release triggered by github action sucks, I think it's better click release by yourself, it could auto generate detailed PR changes between different releases.

**Comment by cofyc** [comment]
`provisioner-2.6.0-alpha.0` and `provisioner-2.5.1` tags are deleted.

**Comment by andyzhangx** [comment]
@cofyc thanks, when shall we cut v2.5.0 release?

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.5.0
