### ISSUE TITLE
No releases since December 2020

### ISSUE THREAD

**Issue by stevehipwell** [kubernetes-sigs/sig-storage-local-static-provisioner#291]
**What happened**:
There have been no releases since December 2020 despite there being a number of commits since then. Is this project still maintained and are you expecting to release these changes at any point soon?

**What you expected to happen**:
n/a

**How to reproduce it**:
n/a

**Anything else we need to know?**:
n/a

**Environment**:
n/a

**Comment by mauriciopoppe** [comment]
I've been working on adding Windows support in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/270, I'm not sure if @cofyc has plans for a release before this feature is complete but after it's complete I'll work on a new release in 2022Q2

**Comment by stevehipwell** [comment]
@mauriciopoppe @cofyc could you take a look at #289 and follow up on the attached PR to fix your `gh-pages` issue?

**Comment by mauriciopoppe** [comment]
I added /ok-to-test to the [test-infra PR](https://github.com/kubernetes/test-infra/pull/25547), unfortunately I don't have permissions to approve it

@cofyc I saw that there are release instructions in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/RELEASE.md but are missing info about the changes needed in the helm chart, what do you suggest to do for a release, we're trying to have a new release with a newer version of the debian-base image in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/295

**Comment by mauriciopoppe** [comment]
I read the [Chart releaser code](https://github.com/helm/chart-releaser-action/blob/62088055651dab7087de02051b5601b15e3772a0/cr.sh#L61-L82) and it wipes out the existing tags in the branch and does everything from scratch, this means that across releases only the latest chart will be visible which is a problem.

A few workarounds:

- Have many copies of the chart by version

```
charts/
  provisioner/
    v2.4.0/
    v2.5.0/
```

- Ask sig-test-infra if they have tools for helm chart publishing
- Do what the github action code does on our own in a post submit prow job, we'll have an entrypoint through cloudbuild.yaml and our input is the git tag, through this entrypoint we would
  - Clone the repo at that tag
  - Copy the contents of `charts/provisioner` to a directory structure that has a version e.g. `charts/provisioner/<tag>`

**Comment by mauriciopoppe** [comment]
I misunderstood what the chart releaser Github action does, it's creating a Github release for the latest tag and hosting a Repository Index yaml file in gh-pages, it looks like we'd need to configure it so that it takes the Changelog from https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/300, I'm a little bit concerned about it being able to create a git tags automatically from changes in the chart version.

**Comment by stevehipwell** [comment]
@mauriciopoppe chart releaser is the idiomatic way to do this. I'd be happy to look at your CI to check out the pattern?

RE the changelog, you'd need a separate one for the chart as it's a separate release artifact.

I'd suggest having a look at the ExternalDNS repo as a good example of this workflow.

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.5.0 is released last month.
