### ISSUE TITLE
E2E tests are no longer passing due to an error on the E2E setup in k/k/test/e2e/framework

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/sig-storage-local-static-provisioner#293]
**What happened**:

I've added a few changes in the e2e tests related with RBAC, the e2e tests are failing while creating the test namespace, I've run the e2e job in PRs where the job was passing successfully but now they're all failing.

These PRs had successful e2e test runs:
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/265
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/279

Still tracking down changes in upstream kubernetes related with the e2e setup, a few interesting PRs taken from the [commit history of k/k/test/e2e/framework](https://github.com/kubernetes/kubernetes/commits/master/test/e2e/framework):

- https://github.com/kubernetes/kubernetes/pull/107763 (and https://github.com/kubernetes/kubernetes/issues/107762)

**How to reproduce it**:

Trigger an e2e test in a dummy PR or in any PR that has successful e2e test runs.

**Comment by mauriciopoppe** [comment]
It looks like as part of the namespace creation we should have a default ServiceAccount on it that's not created and that's why it's timing out.

There's an ongoing issue in upstream kubernetes https://github.com/kubernetes/kubernetes/issues/108307#issuecomment-1074394385

**Comment by mauriciopoppe** [comment]
Found out the issue is in our version of kubernetes which we use to do the e2e framework setup, we were using v1.22 which is no longer compatible with clusters created with 1.24

**Comment by pohly** [comment]
@mauriciopoppe : I can into the same failure. But in my case, namespace creation seems to work reliably with Kubernetes 1.22 and only failed in one test with 1.19.

Can you explain what you meant with "we were using v1.22 which is no longer compatible with clusters created with 1.24" - what is no longer compatible with what, and why?

I assume you mean e2e.test from 1.24 is no longer compatible with a 1.22 cluster (right?), but why?

**Comment by mauriciopoppe** [comment]
@pohly If I remember correctly [our tests](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/hack/run-e2e.sh#L162) which were using k8s v1.22 were always failing during the test setup in a k8s cluster created from k/k/master (we always create a cluster from master for e2e tests) which at the time was 1.24-alpha, I forgot the details but the clues in https://github.com/kubernetes/kubernetes/issues/108307#issuecomment-1074394385 matched what I was seeing in my dev cluster and after updating the k8s library to 1.24 it just worked.

Also, this repo does the e2e setup on its own and doesn't use e2e.test
