### ISSUE TITLE
The canary & post-submit jobs are failing in test-infra

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/sig-storage-local-static-provisioner#297]
**What happened**:

In preparation for a new release I saw that the post submit jobs are failing in test infra:

- Canary job: https://testgrid.k8s.io/sig-storage-image-build#canary-sig-storage-local-static-provisioner-push-images
- Post submit job: https://testgrid.k8s.io/sig-storage-image-build#post-sig-storage-local-static-provisioner-push-images

**Comment by mauriciopoppe** [comment]
I checked that we have 2 places where we're trying to run post-submit

- [sig-storage-local-static-provisioner](https://k8s-testgrid.appspot.com/sig-storage-local-static-provisioner)
  - the canary job is running fine: https://k8s-testgrid.appspot.com/sig-storage-local-static-provisioner#master-canary-build
  - the release job wasn't run in a long time, there are no logs or history for its latest run
- [sig-storage-image-build](https://k8s-testgrid.appspot.com/sig-storage-image-build#canary-sig-storage-local-static-provisioner-push-images) (generated by https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-sig-storage.sh)
  - the canary script uses cloudbuild but the setup is not done yet and the script is broken, I need to update this line https://github.com/kubernetes/test-infra/blob/5ec7217c27b74c9882168b4d81d8c0c8c636d371/config/jobs/image-pushing/k8s-staging-sig-storage.sh#L123
  - the release script uses cloudbuild but the setup is not done yet

Still to decide: which of these post-submit jobs should own the image pushing

- sig-storage-image-build
  - we follow what's done in CSI which is well documented and there's a lot of code already done that supports it
  - we only need a `cloudbuild.yaml` file and it'll get automatically pushed to k8s-staging-sig-storage
  - does CI every week instead of "per push builds"
-  sig-storage-local-static-provisioner
  - more manual, we do have control over the release scripts too in test-infra which unlike image-build are not generated by a script
  - does CI for every commit to master

Probably a combination would also work great, we could take the sig-storage tools built around image publishing and the custom prow jobs for commits to master

**Comment by andyzhangx** [comment]
it's fixed now: https://k8s-testgrid.appspot.com/sig-storage-image-build#post-sig-storage-local-static-provisioner-push-images
