### ISSUE TITLE
Host Local Volume Provisioner container in AWS ECR Public Gallery

### ISSUE THREAD

**Issue by cobookman** [kubernetes-sigs/sig-storage-local-static-provisioner#324]
**Is your feature request related to a problem?/Why is this needed**

Downloading containers from GCR to EKS clusters will have end-users incur internet egress fees.

**Describe the solution you'd like in detail**

Have the CI/CD pipeline also upload the container to ECR Public GALLERY.

**Describe alternatives you've considered**
N/A

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/

**Comment by mauriciopoppe** [comment]
Thanks for the feature request. There's an effort going on with the new url registry.k8s.io https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io) that should help with this problem, currently I don't think that the images of this repo are pushed to the sig-storage release GCR that's behind that URL but there's an effort going on to migrate this repo to use the same GCR as other sig-storage repos (started in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/297#issuecomment-1081254219)

**Comment by andyzhangx** [comment]
@cobookman would this PR(https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/311) solve the issue? This repo is already using `registry.k8s.io`

**Comment by cobookman** [comment]
@andyzhangx believe it does. Thanks!
