### ISSUE TITLE
Missing Volume Metrics `kubelet_volume_stats_*`

### ISSUE THREAD

**Issue by ugur99** [kubernetes-sigs/sig-storage-local-static-provisioner#330]
Hi, we are using local-volume-provisioner and we want to monitor the capacity of PV through `kubelet_volume_stats_*` metrics from kubelet. 

Kubelet does not seem to export the metrics for PV created by this storage class. However metrics for the PV created by CSI backed storage classess are exposed.

I’m not sure whether this is a bug or expected behaviour.

Do you have any ideas about this issue?

Appreciate any suggestions.

**Environment**:
- Kubernetes version : `Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from /etc/os-release):`
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`

- Kernel : `Linux controlplane 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ugur99** [comment]
Sorry for misunderstanding, as far as I realized, local-path-provisioner uses `hostPath` to provision PVs unlikely to the local-static-provisioner. So it explains why it does not have any metrics for PVs. I am closing this issue. Thanks for your interest.

**Comment by whitepiratebaku** [comment]
@ugur99 did you find workaround on this? for monitoring storage?  currently those kubelet_volume_stats* metrics exist for us but shows summed, general value. Like for all PVCs it shows total local disk metrics.

**Comment by ugur99** [comment]
Hi @whitepiratebaku, as a workaround I developed a [simple project](https://github.com/ugur99/local-path-provisioner-pv-metrics-exporter) (but it's kind of experimental, not sure about its a good practice) and it works except a few limitations.

**Comment by whitepiratebaku** [comment]
Thank you @ugur99

**Comment by whitepiratebaku** [comment]
@ugur99 I wonder does PVC storage requests matter? because I see that it on status it shows whole filesystem size as available. So if I give 10gb as request but filesystem has 50GB, then real limit of PVC is 50?

**Comment by ugur99** [comment]
Yes, you're right @whitepiratebaku, actually in [best-practices documentation](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/best-practices.md) separate partitions per volume are recommended for capacity isolation.
