### ISSUE TITLE
Move examples to have all of them in a single location

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/sig-storage-local-static-provisioner#343]
**Is your feature request related to a problem?/Why is this needed**

https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/341/files added missing config to an example in `deployment/kubernetes/example`, however there are more examples in `examples/`. I think we should have a single place for examples.

**Comment by Kartik494** [comment]
Hi @mauriciopoppe if you are ok with it can we move all the `examples/` to `deployment/kubernetes/example` ? if this seems ok to you then please suggest your take on this.

**Comment by Kartik494** [comment]
@mauriciopoppe I would like to give a try on this if anyone not working on this. Please suggest

**Comment by mauriciopoppe** [comment]
I saw other repos and external-provisioner has them in `examples/`, https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver in `examples/kubernetes` too, I think examples or deployment/.../examples would work fine

**Comment by Kartik494** [comment]
@mauriciopoppe thanks for the inputs , i would like to give a try.
/assign

**Comment by mauriciopoppe** [comment]
From a comment in #344:

> I saw that `deployment/kubernetes/example` is an example of installing LVP, `examples/` are example of how LVP is used, with that in mind I think they should be in different places.
