### ISSUE TITLE
Helm -- nodeSelector not applied to windows daemonset

### ISSUE THREAD

**Issue by petercable** [kubernetes-sigs/sig-storage-local-static-provisioner#347]
**What happened**:

Render the helm chart (2.5.1) with the following values.yaml:

```
daemonset:
  nodeSelector:
    my-tag: "true"
```

The windows daemonset contains only:

```
      nodeSelector:
        kubernetes.io/os: windows
```

but the linux daemonset contains:

```
      nodeSelector:
        kubernetes.io/os: linux

        my-tag: "true"
```

**What you expected to happen**:

Both the linux and windows daemonsets should apply the supplied nodeSelectors.

**How to reproduce it**:

```
helm template -f values.yaml test path/to/helm/chart
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by petercable** [comment]
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/3ea2ccc2cd30ccaaf2708a911f99fc75674b5de6/helm/provisioner/templates/daemonset_windows.yaml#L35-L36

**Comment by mauriciopoppe** [comment]
I think adding

```
{{- if .Values.daemonset.nodeSelector }}
        {{ toYaml .Values.daemonset.nodeSelector | nindent 8 }}
{{- end }}
```

should work but at the same time you could have Linux vs Windows specific node selector key values, another option is to go with

```
{{- if .Values.daemonset.nodeSelectorWindows }}
        {{ toYaml .Values.daemonset.nodeSelectorWindows | nindent 8 }}
{{- end }}
```

**Comment by mauriciopoppe** [comment]
This should be fixed in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/353, check the release notes in that PR and the [helm installation docs](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/helm/README.md#install-local-volume-provisioner)
