### ISSUE TITLE
Publish Helm Chart to a Repo

### ISSUE THREAD

**Issue by arthurvanduynhoven** [kubernetes-sigs/sig-storage-local-static-provisioner#35]
Feature Request:

It would be nice be able to use the helm chart from the official incubator/stable repository of helm - https://github.com/helm/charts.

Being able to run `helm install local-static-provisioner -f myconfig.yaml` is more convenient than checking out the code and running numerous helm/kubectl commands to install the local static provisioner.

**Comment by Bessonov** [comment]
go away, evil bot... /remove-lifecycle stale

**Comment by Bessonov** [comment]
still evil... /remove-lifecycle stale

**Comment by pierreozoux** [comment]
As the central helm repo is being deprecated, I think you can close this issue.

**Comment by TBBle** [comment]
This issue is replaced by #199, due to deprecation of the Helm Stable/Incubator charts repo.

**Comment by Bessonov** [comment]
Please, remove the stale bot. I hate the messages from stale bot. I hate to notify all subscribers with /remove-lifecycle stale messages. Stale bot is a good way to show your disrespect to the community.

**Comment by TBBle** [comment]
Note that the Chart repository in the original request has been deprecated, so somewhere else will have to be found to host such a Helm chart. See #199 for details, although that was closed for some reason.

**Comment by viceice** [comment]
I can provide a pr which is using a workflow from [kubernetes-sigs/nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/.github/workflows/helm-chart-release.yml)

Will you accept that?

**Comment by cofyc** [comment]
@viceice welcome!
