### ISSUE TITLE
Missing doc on 2.5.0 version compatibility with K8s versions in readme.md

### ISSUE THREAD

**Issue by hahewlet** [kubernetes-sigs/sig-storage-local-static-provisioner#360]
The current readme, https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/README.md Version Compatibility section does not include the new 2.5.0 release that was made available in July 2022. Can this be updated to indicate the Kubernetes releases this version supports? Thanks!

![image](https://user-images.githubusercontent.com/44618553/211865403-56b29b02-9eb8-451b-9084-e862adb86cc8.png)

**Comment by jmhbnz** [comment]
/assign

Thanks for reporting this, I've raised a pull request to tidy this up and avoid any confusion.
