### ISSUE TITLE
Add the ability to disable the Windows daemonset

### ISSUE THREAD

**Issue by evanfoster** [kubernetes-sigs/sig-storage-local-static-provisioner#381]
I've encountered issues with the Windows local static provisioner daemonset (related to PSPs), and I don't actually need it to be present (we won't be using Windows nodes with it). It would be great to have a way to optionally disable either one of the daemonsets in the `values.yaml` file.

**Comment by mauriciopoppe** [comment]
Thanks for the feature request, I think we could add this as `.common.enableWindows: false` in the helm chart. I'll add some tags so that someone can help with this.

**Comment by evanfoster** [comment]
Hey @mauriciopoppe, thanks for doing that!

**Comment by jennwah** [comment]
Hi @mauriciopoppe, I would like to contribute to this PR as my first issues in `sig-storage-local-static-provisioner`. 
 
 /assign

**Comment by jennwah** [comment]
After reading the source code, we might wanna add a new config field in `ProvisionerConfiguration` for `enableWindwos bool` or `UserConfig` or even `RuntimeConfig` if this field ever needs to be passed down to deeper levels into controller or discoverer or informer. Not very sure where is the entry point for disabling this Windows Daemonset in the source code, perhaps I need some help/guidance into this. I am willing to complete this feature request. 

@mauriciopoppe

**Comment by jennwah** [comment]
Looks like a simple add of `enableWindows` in helm value `common.{..}` and in `daemonset_windows.yaml` should do the job. I have opened a small PR for this new feature here https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/388. Needs approval for `ok-to-test` flag. Thank you :)
