### ISSUE TITLE
Multiple PersistentVolumes from single local device

### ISSUE THREAD

**Issue by hlship** [kubernetes-sigs/sig-storage-local-static-provisioner#398]
**Is your feature request related to a problem?/Why is this needed**

We are using local NVMe SSDs as a fast cache of immutable data from a central database, and are deployed on EKS.
The mapping of a single SSD to a single PersistentVolume (PV) is problematic, as the sizes available from the EC2 instances we use (either 600 or 900 Gb) is rarely a good fit, typically too large, and result in poor utilization of K8s Nodes, because the availability of the limited number of PVs on a Node becomes the overriding constraint on Pod scheduling.

**Describe the solution you'd like in detail**

We would like the option to split the SSD into multiple PVs in some way; for example, a single 600 Gb SSD would be exposed as 6 x 100 Gb PVs.  Ideally, we'd have some direct control over how the split goes (we may want, say, one 300 Gb PV and  3 x 100 Gb PV).  Whether this is controlled by configuration or script, or a mix, is somewhat immaterial.

**Comment by mauriciopoppe** [comment]
The setup of the disk devices and the way they're partitioned is outside the scope of the local-volume-provisioner (LVP). As part of your node bootstrap script you [could partition the disk on your own](https://www.digitalocean.com/community/tutorials/how-to-partition-and-format-storage-devices-in-linux) and then create multiple bind mounts in a single discovery directory which would be scanned by LVP. For example:

```
/mnt/discovery
  /partition-1 --(bind mount)--> /dev/<some partition of your disk> 
  /partition-2 --(bind mount)--> /dev/<some partition of your disk> 
```

**Comment by hlship** [comment]
Thanks for the pointers, I'm working with my Cloud Orchestration team to figure something out.

**Comment by stevehipwell** [comment]
@hlship if you can't customise your node bootstrap (e.g. AKS) you should be able to use an init container on the DaemonSet to do this.
