### ISSUE TITLE
Any plans to cut a new release soon?

### ISSUE THREAD

**Issue by mamccorm** [kubernetes-sigs/sig-storage-local-static-provisioner#438]
Hi there,

Are there any plans to cut a new release shortly? Looks like the last was back in August 2023, but there has been a number of commits in the period since.

Thanks in advance,

**Comment by sclinnell** [comment]
+1 on this request.  There are many vulnerabilities on the image released last year.

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.7.0

**Comment by prasadkatti** [comment]
@andyzhangx - Looks like the [CHANGELOG.md](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/CHANGELOG.md) wasn't updated when the `v2.7.0` release was cut. It was updated with generated content for the previous release, but I don't see any scripts or documentation on how that was done.
