### ISSUE TITLE
Clean up docs (don't mention very old Kubernetes versions)

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/sig-storage-local-static-provisioner#441]
I read this: 

https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md

Some text references very old Kubernetes versions. 

This looks strange to people like who are interested in the project.

**Comment by thisisharrsh** [comment]
Hi @guettli, It appears that the [PR](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/448/files) has updated the [file](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md).

**Comment by guettli** [comment]
@thisisharrsh thank you, closing this issue.
