### ISSUE TITLE
【help】How is the data cleaning performed on the pv after deleting the pvc

### ISSUE THREAD

**Issue by cscowx** [kubernetes-sigs/sig-storage-local-static-provisioner#471]
Hello everyone,

  How is the data cleaning performed on the pv after deleting the pvc

  Is this a few scripts to achieve PV data cleaning?

![image](https://github.com/user-attachments/assets/63922362-2e56-4930-ac8a-f290aef659b4)

![image](https://github.com/user-attachments/assets/4a5af8d1-9d65-401d-8495-c64da05deaeb)

kubectl exec -it pod/production-local-provisioner-local-static-provisioner-br8fh -n test-k8s -- sh

I went into one of the containers and found these scripts in the /scripts directory.Are these scripts used to automatically clean the data on the PV associated backend storage when a PVC is deleted?

![image](https://github.com/user-attachments/assets/e116f4d4-418f-4f77-9cb2-641980e7d0c0)

As an experiment, I overwrote (i.e., emptied) the /scripts directory of the container and found that deleting the PVC still automatically cleaned up all the data on the filesystem associated with the PV

What is the process of the data cleaning mechanism of the PV, and how does it clean all the data on the file system associated with the PV?

Or to put it this way
How does it use a delete logic to clean up all the data on the file system associated with the PV when it hears that the PVC is deleted?

**Comment by andyzhangx** [comment]
When PVC is deleted, the associated PV would be in released state, and pv data would be deleted, code is here:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/16fc083d7d1684931fe974bcaae6eca815d7ec39/pkg/deleter/deleter.go#L68-L70
