### ISSUE TITLE
Dynamic Provisioning Implementation

### ISSUE THREAD

**Issue by petermetz** [kubernetes-sigs/sig-storage-local-static-provisioner#51]
Is this repo the right place to submit a PR with dynamic local volume provisioning?
I read in the documentation that dynamic provisioning is on the roadmap, but wanted to double check because the name of the repo has "static" in it which doesn't look like a good omen.

**Comment by lyyao09** [comment]
Does anyone know how dynamic provisioning  is progressing, and whether there is a release plan?

**Comment by msau42** [comment]
It is unfortunately not progressing. We are looking for someone that can own and architect a solution.

**Comment by cofyc** [comment]
/remove-lifecycle rotten
I've written a design proposal, FYI: https://docs.google.com/document/d/1WtX2lRJjZ03RBdzQIZY3IOvmoYiF5JxDX35-SsCIAfg

**Comment by baurmatt** [comment]
We would still be interested in this functionality! :)

/reopen
/remove-lifecycle rotten

**Comment by cofyc** [comment]
> We would still be interested in this functionality! :)
> 
> /reopen
> /remove-lifecycle rotten

dynamic provisioning will not be done in this project. You can track the progress of the storage capacity tracking feature: https://github.com/kubernetes/enhancements/issues/1472
