### ISSUE TITLE
Prepare a new release

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/sig-storage-local-static-provisioner#57]
Decide if 2.3.1 or 2.4.0.  Taking a quick glance at the commits, it was mostly release tooling and helm chart fixes that went in.  cc @cofyc if there was something major I missed.

/assign

**Comment by cofyc** [comment]
no major changes since 2.3.0

**Comment by msau42** [comment]
@cofyc can you help prepare a new release? Mainly updating CHANGELOG.md and README.md.  If no major changes added and mostly bug fixes, then we can do a 2.3.1
