### ISSUE TITLE
Switch to standard go project layout

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#74]
Why:

- simpler
- newbie friendly

e.g. 

- /provisioner/cmd -> /cmd/local-volume-provisioner
- /utils/ -> cmd/utils/
- merge /provisioner/Makefile with /Makefile
- put some docs under docs/ (new) directory
  - /provisioner/README.md -> /docs/Provisioner.md
  - /provisioner/RELEASE.md  -> /docs/RELEASE.md
  - /provisioner/TODO.md -> /TODO.md
- /provisioner/deployment -> /deployment
- /provisioner/pkg -> /pkg

cc @msau42 What do you think?

**Comment by msau42** [comment]
Sounds good to me! Originally we had one more layer because we had multiple different programs, but now I don't think it's necessary
