### ISSUE TITLE
Enable useNodeNameOnly by default in next major release

### ISSUE THREAD

**Issue by cofyc** [kubernetes-sigs/sig-storage-local-static-provisioner#85]
In most cases, node name as provisioner name is better. 

xref: 

- https://github.com/kubernetes-incubator/external-storage/issues/945
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/faqs.md#pv-with-delete-reclaimpolicy-is-released-but-not-going-to-be-reclaimed

**Comment by gregwebs** [comment]
Should this still be the case? Node names are re-used across different physical instances for both GCP and AWS (under certain circumstances). This then requires disks to be mounted by UUID (which is not the case on GCP) to understand that there are different disks.

**Comment by cofyc** [comment]
not, I'm closing this.
