### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/sig-storage-local-static-provisioner#9]
Migrating from https://github.com/kubernetes-incubator/external-storage/issues/701

Right now everything is manual: creating/pushing containers, updating docs/examples, etc.

At least creating/pushing containers + e2es can be automated with CI.

**Comment by cofyc** [comment]
For creating/pushing containers automatically, we can use postsubmit prow jobs but I don't know how to configure secret credentials in it. 
Alternatively, we can configure travis to build on branches/tags and store quay.io docker credentials on travis site.

**Comment by cofyc** [comment]
https://github.com/kubernetes/test-infra/blob/8845d43219c40c1d9c0f98d24a4454fd34ecaa9c/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L60-L66

The problem is how to configure pusher credentials. I guess this secret is configured manually in prow cluster, because test-infra repo is public.

**Comment by BenTheElder** [comment]
correct, contact go.k8s.io/oncall about setting up credentials

**Comment by cofyc** [comment]
@BenTheElder Thanks!

**Comment by cofyc** [comment]
@BenTheElder hi, I have a few more questions.

Found there is only a few trusted clusters (test-infra-trusted, security) now. According to [this comment](https://github.com/kubernetes/test-infra/blob/49d1dc9a852745ec28f7d84f4edc70610c395077/config/tests/jobs/jobs_test.go#L317), I guess the best place to put trusted jobs for `sig-storage-local-static-provisioner` is `config/jobs/kubernetes-sigs/sig-storage-local-static-provisioner/sig-storage-local-static-provisioner-trusted.yaml`, am I right?

But in which cluster should I run jobs, `test-infra-trusted` or create a new cluster `sig-storage-local-static-provisioner-trusted`?

**Comment by BenTheElder** [comment]
we probably need a new trusted cluster, I'll leave the decision to @fejta
who setup test-infra-trusted, but definitely not the "security" cluster :-)

**Comment by fejta** [comment]
This job is not trusted by test-infra, so we should not put it there.

Do not see why this needs its own cluster. This needs:
* A known-location to push the images
* Credentials that have the right to push images to this location

We can put these credentials into a new secret in the cluster, and then enforce via our presubmits that only jobs in `config/jobs/kubernetes-sigs/sig-storage-local-static-provisioner/sig-storage-local-static-provisioner-trusted.yaml` mount this secret into the container.

**Comment by fejta** [comment]
Your own cluster will also work but IMO most likely overkill.

**Comment by msau42** [comment]
This plan sounds good to me.  Who can we work with to get this setup?

**Comment by cofyc** [comment]
fejta told me how to do on stack. IIUC, there are two steps to get this setup:

- concat http://go.k8s.io/oncall to save credentials in default cluster
- add a unit test to enforce that only jobs (presubmit & periodic) in `kubernetes-sigs/sig-storage-local-static-provisioner/sig-storage-local-static-provisioner-trusted.yaml` can mount secret our secret

**Comment by cofyc** [comment]
/close
Closed by via https://github.com/kubernetes/test-infra/pull/10802.
