### ISSUE TITLE
local-volume-provisioner for arm

### ISSUE THREAD

**Issue by miguelaeh** [kubernetes-sigs/sig-storage-local-static-provisioner#95]
Hi,
I need to configure the local-storage-provisioner for an arm cluster, but the `quay.io/external_storage/local-volume-provisioner` image does not work on arm devices. 
Is it possible to do that? And, if it is, how? Can I get the Dockerfile to change the base image or exists any image for that? Thanks.

**Comment by cofyc** [comment]
Yes, it is possible to do.
We need to build local-volume-provisioner for arm and build an image for it.

**Comment by miguelaeh** [comment]
Hi @cofyc,
thanks for your response. I tried with `local-volume-provisioner-arm64` but it seems that this image do not exists because I get the following error:
`access to the requested resource is not authorized`

**Comment by cofyc** [comment]
sorry, it's not finished yet, can you wait a few days?

**Comment by miguelaeh** [comment]
Of course, 
sorry I understood that it was already finished.

**Comment by cofyc** [comment]
@miguelaeh 
hi, I've pushed images to my personal repository for testing. Could you try `gcr.io/yechengfu-1369/local-volume-provisioner:canary` image in your arm cluster and verify if it works?

**Comment by miguelaeh** [comment]
Hi @cofyc ,
I will test it as soon as I can.
Thank you very much.

**Comment by cofyc** [comment]
btw, official canary images have been pushed too, you can try `quay.io/external_storage/local-volume-provisioner-arm64:canary` instead.

**Comment by MaitreDede** [comment]
Hi @cofyc 

I am using the current `quay.io/external_storage/local-volume-provisioner:canary` (multiarch) on a `arm` arch. I have `exec format error`.
How can I be sure the base docker image is the right arch, and check the bin also is ?

**Comment by cofyc** [comment]
using `file`utility. I've checked it locally, it see

**Comment by cofyc** [comment]
@MaitreDede The bug is fixed, please try again.

This command `docker run -it --entrypoint sh quay.io/external_storage/local-volume-provisioner:canary -c 'apt-get update && apt-get install -y file && file /local-provisioner'` will show the binary information. Can you try it on your arm machine?

**Comment by MaitreDede** [comment]
@cofyc Thanks, it works :)
The binary informations :
```
/local-provisioner: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
```
For information, it is a Raspberry Pi 4 with Raspbian. The ARCH is `arm32v7`. I don't know if there can be differences for `local-provisioner`, but it may be interesting to be more specific on these plateforms.
